// <auto-generated />
using System;
using Feedora_revised.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Feedora_revised.Migrations
{
    [DbContext(typeof(FeedoraRevisedContext))]
    [Migration("20241208075701_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Feedora_revised.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNum")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(891),
                            DateUpdated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(920),
                            Name = "WayneToh",
                            Password = "P@ssword1",
                            PhoneNum = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(923),
                            DateUpdated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(923),
                            Name = "Kokwee",
                            Password = "P@ssword1",
                            PhoneNum = 2,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Feedora_revised.Domain.DeliveryPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNum")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryPartner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(1306),
                            DateUpdated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(1306),
                            Name = "Reina",
                            Password = "P@ssword1",
                            PhoneNum = 5,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(1308),
                            DateUpdated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(1309),
                            Name = "Oc",
                            Password = "P@ssword1",
                            PhoneNum = 6,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Feedora_revised.Domain.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNum")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(1208),
                            DateUpdated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(1208),
                            Name = "Mcdonald",
                            Password = "P@ssword1",
                            PhoneNum = 3,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(1210),
                            DateUpdated = new DateTime(2024, 12, 8, 15, 56, 59, 980, DateTimeKind.Local).AddTicks(1211),
                            Name = "Pizzahut",
                            Password = "P@ssword1",
                            PhoneNum = 4,
                            UpdatedBy = "System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
